
import "./globals.css";
import { DataProvider } from "./context/DataProvider";
import ReduxProvider from "./redux/provider";






export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <html lang="en" data-theme="dark">
      <body  >
      <ReduxProvider>
      <DataProvider>  {children}</DataProvider>
      </ReduxProvider>
        
     
       
      </body>
    </html>
   
    
  );
}
